
spring:
  datasource:
    password: root
#    url: jdbc:mysql://192.180.4.18:3306/authServer
    url: jdbc:mysql://localhost:3306/definer
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true